services:
 dynamodb-web-local:
   #command: "-jar DynamoDBLocal.jar -sharedDb -disableTelemetry -dbPath ./data "
   command: "-jar DynamoDBLocal.jar -sharedDb -inMemory -disableTelemetry"
   image: "amazon/dynamodb-local:latest"
   container_name: dynamodb-web-local
   ports:
     - "8989:8000"
   #volumes:
   #  - "./docker/dynamodb:/home/dynamodblocal/data"
   working_dir: /home/dynamodblocal