#!/bin/sh
set -e

# Generate mosquitto.conf
cat > /mosquitto/config/mosquitto.conf << EOF
# Mosquitto configuration - generated by entrypoint.sh
listener 1884 0.0.0.0
allow_anonymous false
password_file /mosquitto/config/passwd
acl_file /mosquitto/config/acl.conf

# Logging to stdout for CloudWatch
log_dest stdout
log_type all
connection_messages true

# Message limits
message_size_limit 1024

# Connection limits
max_connections ${MQTT_MAX_CONNECTIONS:-1000}
max_keepalive 65535

# No persistence (ephemeral messages)
persistence false
EOF

# Generate passwd file from environment variables
# Each service account: MQTT_{NAME}_USERNAME and MQTT_{NAME}_PASSWORD
touch /mosquitto/config/passwd

# meshtk-proxy service account
mosquitto_passwd -b /mosquitto/config/passwd "${MQTT_MESHTK_USERNAME:-meshtk-proxy}" "${MQTT_MESHTK_PASSWORD}"

# meshobserv service account
mosquitto_passwd -b /mosquitto/config/passwd "${MQTT_MESHOBSERV_USERNAME:-meshobserv}" "${MQTT_MESHOBSERV_PASSWORD}"

# ghosts service account
mosquitto_passwd -b /mosquitto/config/passwd "${MQTT_GHOSTS_USERNAME:-ghosts}" "${MQTT_GHOSTS_PASSWORD}"

# public: remapped identity for validated Meshtastic clients (meshtk proxy rewrites credentials)
mosquitto_passwd -b /mosquitto/config/passwd "public" "31337"

echo "[mosquitto] Config generated, starting mosquitto..."
exec mosquitto -c /mosquitto/config/mosquitto.conf
