/**
 * mesh-ghosts.ts — server-side reader for the meshtk fleet ghosts (Phase 67).
 *
 * Parses the COMMITTED snapshot of apps/run.mqtt/meshtk/meshtk.dc34.yaml
 * (src/data/meshtk-fleet-yaml.ts, regenerated by scripts/sync-meshtk-fleet.mjs;
 * parity-tested against the canonical file) and exposes the `ghost.*` fleet
 * entries for the read-only /admin/ghosts roster. Server-only by usage: page
 * server component + the admin-gated ghost_otp_reveal action. Nothing here is
 * imported by client components — persona prompts carry covert CTF flag phrases
 * and the committed OTP decoys, so this module must never reach a browser
 * bundle.
 */
import { parse } from "yaml";

import { MESHTK_FLEET_YAML } from "@/data/meshtk-fleet-yaml";
import { deriveOtpauthUrl, deriveTotpSecret } from "@/lib/mesh-otp-derive";

export interface GhostChatResponse {
  type: string;
  messages: string[];
  requiresOtp: boolean;
  unlocksChatMode: boolean;
}

export interface MeshGhost {
  /** Fleet Id, e.g. "ghost.goldstein" — the HKDF domain-separation key. */
  id: string;
  /** Id with the "ghost." prefix stripped, e.g. "goldstein". */
  slug: string;
  description: string;
  behaviours: string[];
  shortNameTmpl?: string;
  longNameTmpl?: string;
  nodeDbPath?: string;
  movement?: { type?: string; gpxFile?: string; travel?: string };
  chatbot: GhostChatResponse[];
  /** Full persona prompt (contains the covert flag phrase — admin eyes only). */
  systemPrompt?: string;
  /** Covert CTF code extracted from the prompt ("the secret code is 'X'"). */
  flagCode?: string;
  /** Committed otpauth URL from the YAML (its secret is a decoy once meshtk#10 is live). */
  committedOtpauth?: string;
  hasOtp: boolean;
}

/* eslint-disable @typescript-eslint/no-explicit-any -- defensive walk of parsed YAML */

function str(v: any): string | undefined {
  return typeof v === "string" && v !== "" ? v : undefined;
}

function toGhost(entry: any): MeshGhost | null {
  const id = str(entry?.Id);
  if (!id || !id.startsWith("ghost.")) return null;

  const chatbot: GhostChatResponse[] = Array.isArray(entry.ChatBot)
    ? entry.ChatBot.map((r: any): GhostChatResponse => ({
        type: str(r?.Type) ?? "unknown",
        messages: Array.isArray(r?.Message) ? r.Message.filter((m: any) => typeof m === "string") : [],
        requiresOtp: r?.RequiresOTP === true,
        unlocksChatMode: r?.UnlocksChatMode === true,
      }))
    : [];

  const movementRaw = Array.isArray(entry.Movement) ? entry.Movement[0] : undefined;
  const systemPrompt = str(entry.OpenAISystemPrompt);
  const flagCode = systemPrompt?.match(/secret code is '([^']+)'/)?.[1];
  const committedOtpauth = str(entry.OtpUrl);

  return {
    id,
    slug: id.slice("ghost.".length),
    description: str(entry.Description) ?? id,
    behaviours: Array.isArray(entry.BehaviourTag)
      ? entry.BehaviourTag.filter((t: any) => typeof t === "string")
      : [],
    shortNameTmpl: str(entry.ShortNameTmpl),
    longNameTmpl: str(entry.LongNameTmpl),
    nodeDbPath: str(entry.NodeDbPath),
    movement: movementRaw
      ? {
          type: str(movementRaw.Type),
          gpxFile: str(movementRaw.GPXFile),
          travel: str(movementRaw.Travel),
        }
      : undefined,
    chatbot,
    systemPrompt,
    flagCode,
    committedOtpauth,
    hasOtp: committedOtpauth !== undefined,
  };
}

/* eslint-enable @typescript-eslint/no-explicit-any */

let cache: MeshGhost[] | null = null;

/** All ghost.* fleet entries from the committed snapshot (parsed once per process). */
export function loadMeshGhosts(): MeshGhost[] {
  if (!cache) {
    const doc = parse(MESHTK_FLEET_YAML) as { Fleet?: unknown[] };
    cache = (doc.Fleet ?? [])
      .map(toGhost)
      .filter((g): g is MeshGhost => g !== null);
  }
  return cache;
}

export function getMeshGhost(ghostId: string): MeshGhost | undefined {
  return loadMeshGhosts().find((g) => g.id === ghostId);
}

// ---------------------------------------------------------------------------
// CTF linkage
// ---------------------------------------------------------------------------

/** The slice of a Ctf row this module needs (structural — no entity import). */
export interface CtfRowLike {
  challenge: string;
  enabled?: boolean;
  answerType?: string;
  otp?: { secret?: string };
}

export interface GhostCtfLink {
  challenge: string;
  enabled: boolean;
  answerType?: string;
  /**
   * How this row's OTP secret relates to the ghost's:
   *  - "derived":   equals the derived secret → in sync with a derivation-enabled bot
   *  - "committed": equals the YAML decoy → STALE once the fleet redeploys with meshtk#10
   *  - "none":      row has no OTP secret (e.g. the static half of a chain)
   *  - "other":     has a secret matching neither (manually rotated)
   */
  secretState: "derived" | "committed" | "none" | "other";
}

/**
 * Join a ghost to its Ctf rows. A row matches when its challenge name contains
 * the ghost's slug (the DC33 chains are "<persona>" + "<persona>-otp") OR its
 * otp.secret equals the ghost's committed or derived secret. `serverSecret`
 * (MESHTK_GHOST_KEY_SECRET) is optional — without it, secretState can still
 * report "committed" staleness but never "derived".
 */
export function ghostCtfLinks(
  ghost: MeshGhost,
  ctfRows: CtfRowLike[],
  serverSecret?: string,
): GhostCtfLink[] {
  let committedSecret: string | undefined;
  let derivedSecret: string | undefined;
  if (ghost.committedOtpauth) {
    try {
      committedSecret =
        new URL(ghost.committedOtpauth).searchParams.get("secret") ?? undefined;
      if (serverSecret && committedSecret) {
        derivedSecret = deriveTotpSecret(serverSecret, ghost.id, committedSecret);
      }
    } catch {
      // Malformed committed URL — name-based matching still applies below.
    }
  }

  const links: GhostCtfLink[] = [];
  for (const row of ctfRows) {
    const rowSecret = row.otp?.secret;
    const nameMatch = row.challenge.toLowerCase().includes(ghost.slug.toLowerCase());
    const secretMatch =
      rowSecret !== undefined &&
      (rowSecret === committedSecret || rowSecret === derivedSecret);
    if (!nameMatch && !secretMatch) continue;

    let secretState: GhostCtfLink["secretState"];
    if (rowSecret === undefined) secretState = "none";
    else if (derivedSecret !== undefined && rowSecret === derivedSecret) secretState = "derived";
    else if (rowSecret === committedSecret) secretState = "committed";
    else secretState = "other";

    links.push({
      challenge: row.challenge,
      enabled: row.enabled === true,
      answerType: row.answerType,
      secretState,
    });
  }
  return links.sort((a, b) => a.challenge.localeCompare(b.challenge));
}

// ---------------------------------------------------------------------------
// OTP reveal (admin-gated caller: /api/admin/qr ghost_otp_reveal)
// ---------------------------------------------------------------------------

export interface GhostOtpReveal {
  ghostId: string;
  /** false ⇒ MESHTK_GHOST_KEY_SECRET is unset in this environment. */
  configured: boolean;
  otpauth?: string;
  secret?: string;
  committedSecret?: string;
}

/**
 * The seed a derivation-enabled bot (meshtk#10) actually validates, as a full
 * otpauth URL ready for an authenticator QR. Returns null for an unknown ghost
 * or one with no OtpUrl; `configured:false` when the server secret is unset
 * (the roster renders, the panel explains). NEVER call outside the admin gate.
 */
export function revealGhostOtp(ghostId: string): GhostOtpReveal | null {
  const ghost = getMeshGhost(ghostId);
  if (!ghost?.committedOtpauth) return null;

  const serverSecret = process.env.MESHTK_GHOST_KEY_SECRET;
  if (!serverSecret) return { ghostId, configured: false };

  const { otpauth, secret, committedSecret } = deriveOtpauthUrl(
    serverSecret,
    ghost.id,
    ghost.committedOtpauth,
  );
  return { ghostId, configured: true, otpauth, secret, committedSecret };
}
